[PAGOPA-2113] feat: Add Recovery Cron
pagopa/pagopa-wisp-converter pull request #105
Opened 2024-09-16 14:00 UTC by cap-ang

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-09-18 07:15 UTC, andrea-deri commented on src/main/java/it/gov/pagopa/wispconverter/repository/RTRepository.java
> +    @Query("SELECT * FROM c WHERE IS_NULL(c.rt) AND c._ts >= DateTimeToTimestamp(@dateFrom) / 1000 and c._ts <= DateTimeToTimestamp(@dateTo) / 1000")
Can the order of the `WHERE` clauses be reversed? I think if we filter first with `IS_NULL(c.rt)` we may spend too much RUs if there are too many RT to be reconciled (that's an edge case, but it is better to be save).
Ditto for the query before this.

2024-09-18 07:46 UTC, andrea-deri commented on src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
> +                this.recoverReceiptKO(ci, MOCK_NOTICE_NUMBER, iuv, sessionId, ccp, dateFromString, dateToString);
As seen together in previous calls,`MOCK_NOTICE_NUMBER` can be used for that cases where no notice number is generated. But if there are so much occurrence of this case, how will this "mocked" NAV behave? If the TTL in cache is a standard value (1d), will its presence causes problems during following recoveries? I think not because it is overwritten by `insert` operation of the Redis client, but I would ask you to confirm this.

2024-09-18 07:49 UTC, andrea-deri commented on src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
> +    public void recoverReceiptKO(String ci, String noticeNumber, String iuv, String sessionId, String ccp, String dateFrom, String dateTo) {
Maybe can be useful to set the TTL value as input so you can define different durations for certain cases (i.e. the one with "mock" notice number, to make the life of this key very short). What do you think?

2024-09-18 07:55 UTC, andrea-deri commented on src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
> +            MDC.put(Constants.MDC_BUSINESS_PROCESS, "receipt-ko");
IIRC, during analysis in UAT/PROD we found that the field `insertTimestamp` is not defined in RE event: it is defined by controller's interceptor and set only if the REST API is called, so it is not defined automatically. In case I am not mistaken, can you define an explicit `MDC.put()` for `insertedTimestamp`?

2024-09-18 07:58 UTC, andrea-deri requested changes
I have written some feedback about the new APIs, in general a nice job!

2024-09-18 10:17 UTC, pasqualespica commented on src/main/java/it/gov/pagopa/wispconverter/repository/ReEventRepository.java
> +    @Query(
here could be useful [know the RU consumption](https://stackoverflow.com/questions/58810055/how-can-you-get-the-ru-s-consumed-in-a-cosmosdb-query-in-with-pymongo)

but to avoid consumption to RU in main instance use the read region by [preferredLocations_](https://github.com/pagopa/pagopa-biz-events-service/blob/46d60673767f6656cd867bf756b892579342a23b/report/src/utils/utils.js#L12-L26)

2024-09-18 10:36 UTC, pasqualespica requested changes
LGTM

2024-09-18 10:36 UTC, pasqualespica commented on src/main/java/it/gov/pagopa/wispconverter/scheduler/RecoveryScheduler.java
> +@ConditionalOnProperty(name = "cron.job.schedule.recovery.enabled", matchIfMissing = true)
default `false`

2024-09-18 10:36 UTC, pasqualespica commented on src/main/java/it/gov/pagopa/wispconverter/scheduler/RecoveryScheduler.java
> +    // UNTIL_N_HOURS_AGO: upperbound for a payment session (?)
to avoid mistake to manage not error RPT configure `UNTIL_N_HOURS_AGO` too as param, default `3h`

2024-09-18 10:36 UTC, pasqualespica commented on helm/values-prod.yaml
> +    CRON_JOB_SCHEDULE_RECOVERY_ENABLED: 'true'
add cron spring doc

2024-09-18 10:36 UTC, pasqualespica commented on src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
> +                this.recoverReceiptKO(ci, MOCK_NOTICE_NUMBER, iuv, sessionId, ccp, dateFromString, dateToString);
it works because every RT to recover is processed one by one and the previosuly cache value is removed.

2024-09-18 10:36 UTC, pasqualespica commented on src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
> +                this.recoverReceiptKO(ci, MOCK_NOTICE_NUMBER, iuv, sessionId, ccp, dateFromString, dateToString);
📓 with @andrea-deri obersaviotn @cap-ang we can't use parallel stream recover 
check if it's possible to recover without this info

2024-09-18 10:36 UTC, pasqualespica commented on src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
> +                    log.info("[RECOVERY-MISSING-RT] Recovery with receipt-ko for ci = {}, iuv = {}, ccp = {}, sessionId = {}", ci, iuv, ccp, sessionId);
should be useful add dash tail on WISP Dash

2024-09-18 12:54 UTC, cap-ang commented on src/main/java/it/gov/pagopa/wispconverter/repository/CacheRepository.java
> +        if(deleteIfAlreadyExists && hasKey(key))
This method deletes the key only if the key exists and the value `deleteIfAlreadyExists` (stands for _overwrite_) is true, otherwise it does nothing.

2024-09-18 12:56 UTC, cap-ang commented on src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
> +                this.recoverReceiptKO(ci, MOCK_NOTICE_NUMBER, iuv, sessionId, ccp, dateFromString, dateToString);
I agree, if we use this [method](https://github.com/pagopa/pagopa-wisp-converter/blob/main/src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java#L708), the problem (_RCPC_) of cache and parallel will not arise

2024-09-18 12:57 UTC, cap-ang commented on src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
> +    public void recoverReceiptKO(String ci, String noticeNumber, String iuv, String sessionId, String ccp, String dateFrom, String dateTo) {
It's a case covered by `deleteIfAlreadyExists` to `true`

the problem disappears with _RCPC_ solution.

2024-09-18 13:40 UTC, cap-ang commented on src/main/java/it/gov/pagopa/wispconverter/repository/CacheRepository.java
> +        if(deleteIfAlreadyExists && hasKey(key))
Maybe is useless for my use case because `redisSimpleTemplate.opsForValue().set(...)` always overwrite value

2024-09-18 13:56 UTC, cap-ang commented on src/main/java/it/gov/pagopa/wispconverter/repository/CacheRepository.java
> +        if(deleteIfAlreadyExists && hasKey(key))
solved in [4e4312c](https://github.com/pagopa/pagopa-wisp-converter/pull/105/commits/4e4312c77bfb6568bfbb6adc1547c253b4798b3a)

2024-09-18 13:56 UTC, cap-ang commented on src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
> +                this.recoverReceiptKO(ci, MOCK_NOTICE_NUMBER, iuv, sessionId, ccp, dateFromString, dateToString);
solved in [4e4312c](https://github.com/pagopa/pagopa-wisp-converter/pull/105/commits/4e4312c77bfb6568bfbb6adc1547c253b4798b3a)

2024-09-18 13:56 UTC, cap-ang commented on src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
> +    public void recoverReceiptKO(String ci, String noticeNumber, String iuv, String sessionId, String ccp, String dateFrom, String dateTo) {
solved in [4e4312c](https://github.com/pagopa/pagopa-wisp-converter/pull/105/commits/4e4312c77bfb6568bfbb6adc1547c253b4798b3a)

2024-09-18 14:15 UTC, cap-ang commented on helm/values-prod.yaml
> +    CRON_JOB_SCHEDULE_RECOVERY_ENABLED: 'true'
solved in [26a613c](https://github.com/pagopa/pagopa-wisp-converter/pull/105/commits/26a613c5103083f309704146c3cb04ab0621fb76)

2024-09-18 14:15 UTC, cap-ang commented on src/main/java/it/gov/pagopa/wispconverter/scheduler/RecoveryScheduler.java
> +    // UNTIL_N_HOURS_AGO: upperbound for a payment session (?)
solved in [26a613c](https://github.com/pagopa/pagopa-wisp-converter/pull/105/commits/26a613c5103083f309704146c3cb04ab0621fb76)

2024-09-18 14:53 UTC, cap-ang commented on src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
> +            MDC.put(Constants.MDC_BUSINESS_PROCESS, "receipt-ko");
solved in https://github.com/pagopa/pagopa-wisp-converter/pull/105/commits/84346609bb3ce6fa13b6653d01750cde7202399e

2024-09-20 08:15 UTC, andrea-deri commented on src/main/java/it/gov/pagopa/wispconverter/repository/RTRepository.java
> +    @Query("SELECT * FROM c WHERE IS_NULL(c.rt) AND c._ts >= DateTimeToTimestamp(@dateFrom) / 1000 and c._ts <= DateTimeToTimestamp(@dateTo) / 1000")
I didn't know that, I thought that queries worked the same way as on classic DBs, where the indexes having to be used in a certain predetermined order. Thanks for the info!

2024-09-23 09:47 UTC, cap-ang commented on src/main/java/it/gov/pagopa/wispconverter/repository/ReEventRepository.java
> +    @Query(
I've created a dedicated [PR](https://github.com/pagopa/pagopa-wisp-converter/pull/118) to address the change request

2024-10-02 10:29 UTC, cap-ang commented on src/main/java/it/gov/pagopa/wispconverter/repository/ReEventRepository.java
> +    @Query(
it must read from secondary

2024-10-02 10:30 UTC, cap-ang commented on src/main/java/it/gov/pagopa/wispconverter/repository/RTRepository.java
> +    List<RTEntity> findPendingRT(@Param("dateFrom") String dateFrom, @Param("dateTo") String dateTo);
it must read from secondary

2024-10-02 13:57 UTC, pasqualespica approved these changes
🚀

2024-10-02 13:59 UTC, merged