[PAGOPA-2104] feat: Add new recovery by IUV API
pagopa/pagopa-wisp-converter pull request #106
Opened 2024-09-16 15:49 UTC by cap-ang

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-09-18 19:53 UTC, cap-ang commented on src/main/java/it/gov/pagopa/wispconverter/controller/RecoveryController.java
> +                return ResponseEntity.ok(String.format("RPT with CI %s and IUV %s recovered via API", ci, iuv));
solved in https://github.com/pagopa/pagopa-wisp-converter/pull/106/commits/66e430def27e0eb24568ee431aeaf4eddf149962 with regex validation

2024-09-19 09:20 UTC, jacopocarlini requested changes

2024-09-19 09:20 UTC, jacopocarlini commented on src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
> +    public boolean recoverReceiptKO(String creditorInstitution, String iuv, String dateFrom, String dateTo) {
send the `receiptKO` using sessionId instead

2024-09-20 07:09 UTC, cap-ang commented on src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
> +    public boolean recoverReceiptKO(String creditorInstitution, String iuv, String dateFrom, String dateTo) {
the `paaInviaRT-` is invoked using the `sessionId`. What do you mean exactly? The API input is `IUV` so in the function you mentioned we know the `IUV` but not the `sessionId`

2024-09-23 15:50 UTC, jacopocarlini approved these changes
LGTM 💪

2024-09-24 13:53 UTC, merged