[PAGOPA-2109] custom client
pagopa/pagopa-wisp-converter pull request #98
Opened 2024-09-12 09:53 UTC by jacopocarlini

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-09-13 06:56 UTC, andrea-deri commented on src/main/java/it/gov/pagopa/wispconverter/config/client/custom/ApiConfigCacheApiClient.java
> +                    Thread.sleep(super.getWaitTimeMillis());
How long is the waiting time used? Can be defined as parameterized variable (like `max-retry`) in order to control it?

2024-09-13 07:12 UTC, andrea-deri requested changes
In general, it is a good proposal! 
I have doubts about a few points to which I have added comments. A fundamental question: has this new handling been explicitly tested on a service (e.g. IUV-Generator) that times out?

2024-09-13 07:20 UTC, jacopocarlini commented on src/main/java/it/gov/pagopa/wispconverter/config/client/custom/ApiConfigCacheApiClient.java
> +        while (attempts < super.getMaxAttemptsForRetry()) {
I missed the `break` operation 😅

2024-09-13 07:29 UTC, jacopocarlini commented on src/main/java/it/gov/pagopa/wispconverter/config/client/custom/ApiConfigCacheApiClient.java
> +                    Thread.sleep(super.getWaitTimeMillis());
ok, I can add the parameters. The default value is 10 millisec

2024-09-13 09:09 UTC, jacopocarlini commented
> In general, it is a good proposal! I have doubts about a few points to which I have added comments. A fundamental question: has this new handling been explicitly tested on a service (e.g. IUV-Generator) that times out?

Yes, I did.

2024-09-16 12:47 UTC, FedericoRuzzier commented on src/main/java/it/gov/pagopa/wispconverter/config/client/custom/CheckoutApiClient.java
> +            if (cause instanceof HttpServerErrorException || ((HttpClientErrorException) cause).getStatusCode().equals(HttpStatus.TOO_MANY_REQUESTS)) {
Add log to explicit the error which raised the retry

2024-09-16 12:49 UTC, FedericoRuzzier commented on src/main/java/it/gov/pagopa/wispconverter/config/client/custom/ApiConfigCacheApiClient.java
> +                attempts = handleRetry(runtimeException, attempts);
Ditto log

2024-09-16 12:53 UTC, merged